# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: strings.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstrings.proto\"&\n\x08InString\x12\x0c\n\x04str1\x18\x01 \x01(\t\x12\x0c\n\x04str2\x18\x02 \x01(\t\"\x1b\n\tOutString\x12\x0e\n\x06strout\x18\x01 \x01(\t\"\x1a\n\x07LevDist\x12\x0f\n\x07message\x18\x01 \x01(\x05\"\x17\n\x04\x43omp\x12\x0f\n\x07message\x18\x01 \x01(\x08\x32}\n\nStringsOps\x12(\n\rConcatStrings\x12\t.InString\x1a\n.OutString\"\x00\x12(\n\x0fLevenshteinDist\x12\t.InString\x1a\x08.LevDist\"\x00\x12\x1b\n\x05\x45qual\x12\t.InString\x1a\x05.Comp\"\x00\x62\x06proto3')



_INSTRING = DESCRIPTOR.message_types_by_name['InString']
_OUTSTRING = DESCRIPTOR.message_types_by_name['OutString']
_LEVDIST = DESCRIPTOR.message_types_by_name['LevDist']
_COMP = DESCRIPTOR.message_types_by_name['Comp']
InString = _reflection.GeneratedProtocolMessageType('InString', (_message.Message,), {
  'DESCRIPTOR' : _INSTRING,
  '__module__' : 'strings_pb2'
  # @@protoc_insertion_point(class_scope:InString)
  })
_sym_db.RegisterMessage(InString)

OutString = _reflection.GeneratedProtocolMessageType('OutString', (_message.Message,), {
  'DESCRIPTOR' : _OUTSTRING,
  '__module__' : 'strings_pb2'
  # @@protoc_insertion_point(class_scope:OutString)
  })
_sym_db.RegisterMessage(OutString)

LevDist = _reflection.GeneratedProtocolMessageType('LevDist', (_message.Message,), {
  'DESCRIPTOR' : _LEVDIST,
  '__module__' : 'strings_pb2'
  # @@protoc_insertion_point(class_scope:LevDist)
  })
_sym_db.RegisterMessage(LevDist)

Comp = _reflection.GeneratedProtocolMessageType('Comp', (_message.Message,), {
  'DESCRIPTOR' : _COMP,
  '__module__' : 'strings_pb2'
  # @@protoc_insertion_point(class_scope:Comp)
  })
_sym_db.RegisterMessage(Comp)

_STRINGSOPS = DESCRIPTOR.services_by_name['StringsOps']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INSTRING._serialized_start=17
  _INSTRING._serialized_end=55
  _OUTSTRING._serialized_start=57
  _OUTSTRING._serialized_end=84
  _LEVDIST._serialized_start=86
  _LEVDIST._serialized_end=112
  _COMP._serialized_start=114
  _COMP._serialized_end=137
  _STRINGSOPS._serialized_start=139
  _STRINGSOPS._serialized_end=264
# @@protoc_insertion_point(module_scope)
